apiVersion: v1
kind: Service
metadata:
  name: argocd-gitops-demo
  namespace: argocd-gitops-demo
spec:
  selector:
    app: argocd-gitops-demo
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
